FinEmotionLog/urls.py
from django.urls import path
from django.contrib import admin
from EmotionTracker.views import home_view, emotion_entry_view, progress_view, chatbot_view, signup, user_login, user_logout, emotion_entry, feedback_view, transcribe_audio, analyze_emotion,record_emotion_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    
    path('EmotionLog/RegEmocion/', emotion_entry_view, name='emotion_entry'),
    path('EmotionLog/ValidacionProgreso/', progress_view, name='progress'),
    path('EmotionLog/Chatbot/', chatbot_view, name='chatbot'),
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('emotion_entry/', emotion_entry, name='emotion_entry'),
    path('feedback/', feedback_view, name='feedback'),
    path('record_emotion/', record_emotion_view, name='record_emotion'),
    path('transcribe_audio/', transcribe_audio, name='transcribe_audio'),
    path('analyze_emotion/', analyze_emotion, name='analyze_emotion'),
] 

EmotionTracker/models.py
from django.db import models
from django.contrib.auth.models import User

class EmotionEntry(models.Model):
    user = models.CharField(max_length=100)
    emotion_level = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    emotion_type = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    activity = models.CharField(max_length=100, null=True, blank=True) 

class Profile(models.Model):
    USER_TYPE_CHOICES = [
        ('cliente', 'Cliente'),
        ('psicologo', 'Psicólogo'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='cliente')

    def __str__(self):
        return self.user.username

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    opinion = models.TextField()
    suggestions = models.TextField(default='')  # Definir un valor predeterminado aquí
    useful = models.BooleanField()
    date = models.DateTimeField(auto_now_add=True)

class EmotionRecording(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    emotion_level = models.CharField(max_length=255)
    description = models.TextField()
    audio_file = models.FileField(upload_to='recordings/')
    video_file = models.FileField(upload_to='recordings/', null=True, blank=True)
    transcription = models.TextField(null=True, blank=True)
    analyzed_emotion = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"Recording at {self.created_at}"

EmotionTracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import EmotionEntry
from .models import Feedback
from .models import EmotionRecording

class SignUpForm(UserCreationForm):
    USER_TYPE_CHOICES = [
        ('cliente', 'Cliente'),
        ('psicologo', 'Psicólogo'),
    ]
    user_type = forms.ChoiceField(choices=USER_TYPE_CHOICES, required=True, label='Tipo de usuario')

    class Meta:
        model = User
        fields = ('username', 'user_type', 'password1', 'password2', 'email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_type = self.cleaned_data['user_type']
        if commit:
            user.save()
        return user

class EmotionEntryForm(forms.ModelForm):
    class Meta:
        model = EmotionEntry
        fields = ['emotion_level', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Describe tus emociones aquí...'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['emotion_level'].initial = 3
        self.fields['emotion_level'].widget.attrs.update({'class': 'form-control'})
        

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['opinion', 'suggestions', 'useful']  # Añadir los campos necesarios
        widgets = {
            'opinion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'suggestions': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'useful': forms.RadioSelect(choices=[(True, 'Sí'), (False, 'No')]),
        }


class EmotionRecordingForm(forms.ModelForm):
    class Meta:
        model = EmotionRecording
        fields = ['emotion_level', 'description', 'audio_file', 'video_file']

from django import forms

class VideoUploadForm(forms.Form):
    video_file = forms.FileField(label='Seleccionar archivo de video')


EmotionTracker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.utils.timezone import now, localtime
from .models import EmotionEntry, Profile, EmotionRecording, Feedback
from .forms import (SignUpForm, EmotionEntryForm, FeedbackForm,
                    EmotionRecordingForm, VideoUploadForm)
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import io
import base64
import requests
import speech_recognition as sr
from collections import Counter
import cv2
import numpy as np
from tensorflow.keras.models import load_model
from django.views.decorators.csrf import csrf_exempt




def get_previous_emotion(user):
    try:
        last_entry = EmotionEntry.objects.filter(user=user).latest('created_at')
        return last_entry.emotion_level
    except EmotionEntry.DoesNotExist:
        return "No hay entradas anteriores."

def analyze_emotion(description):
    url = 'https://fd1f-167-0-128-69.ngrok-free.app/analisis?text='
    response = requests.get(url + description)
    
    if response.status_code == 200:
        data = response.json()
        emotion = data.get('emotion')
        return emotion
    else:
        return None
    
@login_required
def emotion_entry(request):
    if request.method == 'POST':
        form = EmotionEntryForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = request.user
            entry.emotion_type = analyze_emotion(entry.description)
            entry.save()
            messages.success(request, 'Emoción registrada con éxito.')
            return redirect('home')  # Redirige a la página de inicio
        else:
            messages.error(request, 'Hubo un error al registrar tu emoción. Por favor, intenta de nuevo.')
    else:
        form = EmotionEntryForm()

    yesterday = timezone.now().date() - timezone.timedelta(days=1)
    previous_entry = EmotionEntry.objects.filter(user=request.user, date__date=yesterday).first()

    previous_emotion = previous_entry.emotion_type if previous_entry else 'No hay datos del día anterior'

    context = {
        'form': form,
        'previous_emotion': previous_emotion,
        'date': timezone.now().date(),
        'time': timezone.localtime(timezone.now()).time()
    }
    return render(request, 'EmotionTracker/emotion_entry.html', context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # Recarga la instancia del usuario para actualizar el perfil.
            # Asegúrate de que el perfil está creado antes de acceder a él.
            Profile.objects.create(user=user)
            user.profile.user_type = form.cleaned_data.get('user_type')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'EmotionTracker/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'EmotionTracker/login.html', {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return redirect('home')

def home_view(request):
    context = {
        'nav_options': ['Recursos', 'Libros', 'Videos', 'Coaching', 'Eventos'],
    }
    return render(request, 'EmotionTracker/home.html', context)


def emotion_entry_view(request):
    confirmation_message = None

    if request.method == 'POST':
        # Procesar el formulario de registro de emoción
        emotion_level = request.POST.get('emotion_level')
        user = request.POST.get('user')
        
        # Crear un nuevo registro de emoción en el modelo EmotionEntry
        emotion_entry = EmotionEntry(user=user, emotion_level=emotion_level)
        emotion_entry.save()
        
        # Agregar mensaje de confirmación
        confirmation_message = f"Emoción guardada: Usuario: {user}, Nivel de emoción: {emotion_level}"
        
    # Obtener las opciones para validar el progreso y volver al inicio
    options = {'validation_url': '/EmotionLog/ValidacionProgreso/', 'home_url': '/'}
    
    # Renderizar el formulario de registro de emoción utilizando el template específico
    return render(request, 'EmotionTracker/emotion_entry.html', {'confirmation_message': confirmation_message, 'options': options})



@login_required
def feedback_view(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.user = request.user
            feedback.save()
            return redirect('home')  # Redirigir al usuario a la página de inicio después de enviar el feedback
    else:
        form = FeedbackForm()
    return render(request, 'EmotionTracker/feedback_thanks.html', {'form': form})

def progress_view(request):
    # Obtener los registros de emoción del usuario
    user = request.user  # Suponiendo que el usuario está autenticado
    emotion_entries = EmotionEntry.objects.filter(user=user)
    
    # Contar la cantidad de veces que se repite cada tipo de emoción
    emotion_counts = Counter(entry.emotion_type for entry in emotion_entries)
    
    # Generar la gráfica de barras
    fig, ax = plt.subplots()
    ax.bar(emotion_counts.keys(), emotion_counts.values())
    ax.set_xlabel('Tipo de Emoción')
    ax.set_ylabel('Cantidad')
    ax.set_title(f'Cantidad de veces que se repite cada emoción - {user.username}')
    
    # Convertir la gráfica a una imagen codificada en base64
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image_base64 = base64.b64encode(buffer.read()).decode('utf-8')
    
    context = {
        'emotion_chart': image_base64,
        'home_url': '/',  # Enlace para volver a la página de inicio
        'emotion_entry_url': '/EmotionLog/RegEmocion/',  # Enlace para registrar emociones
    }
    return render(request, 'EmotionTracker/progress.html', context)

def chatbot_view(request):
    return render(request, 'EmotionTracker/chatbot.html')


@login_required
def record_emotion_view(request):
    return render(request, 'EmotionTracker/record_emotion.html')

@csrf_exempt
def transcribe_audio(request):
    if request.method == 'POST':
        audio_file = request.FILES['file']
        
        recognizer = sr.Recognizer()
        with sr.AudioFile(audio_file) as source:
            audio_data = recognizer.record(source)
            try:
                transcription = recognizer.recognize_google(audio_data, language='es-ES')
                
                # Analizar la emoción de la transcripción
                emotion = analyze_emotion(transcription)
                
                # Crear una nueva entrada de emoción y guardarla en la base de datos
                emotion_entry = EmotionEntry(
                    description=transcription,
                    emotion_type=emotion,
                    emotion_level=0  # Ajusta esto según tu modelo de datos
                )
                emotion_entry.save()
                
                return JsonResponse({'transcription': transcription})
            except sr.UnknownValueError:
                return JsonResponse({'transcription': 'No se pudo transcribir el audio.'}, status=400)
            except sr.RequestError:
                return JsonResponse({'transcription': 'Error en el servicio de transcripción.'}, status=500)

    return JsonResponse({'error': 'Método no permitido'}, status=405)


def get_emotion_analysis(description):
    url = 'https://fd1f-167-0-128-69.ngrok-free.app/analisis?text='
    response = requests.get(url + description)
    if response.status_code == 200:
        data = response.json()
        emotion = data.get('emotion')
        return emotion
    else:
        return None

def get_label(predict):
    labels = {
        0: "Triste",
        1: "Enojado",
        2: "Tranquilo",
        3: "Ansioso",
        4: "Feliz"
    }
    max_prob = np.max(predict)
    if max_prob < 0.6:
        return 'Triste'
    return labels[np.argmax(predict)]

def detect_emotion(request):
    if request.method == 'POST':
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            video_file = request.FILES['video_file']

            cap = cv2.VideoCapture(video_file)

            with custom_object_scope({"KerasLayer": hub.KerasLayer}):
                modelo = load_model('modelo_entrenado.h5')

            emotions_detected = []

            while True:
                ret, frame = cap.read()

                if not ret:
                    break  
                img = cv2.resize(frame, (224, 224))
                img = np.expand_dims(img, axis=0)

EmotionTracker/templates/EmotionTracker/base_p.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de emociones</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'EmotionTracker/css/styles.css' %}">
    <style>
        .bg-primary {
            background-color: #D8BFD8 !important; /* Color lila pálido */
        }
        .text-primary {
            color: #D8BFD8 !important; /* Color lila pálido */
        }
        .btn-secondary {
            background-color: #D8BFD8 !important; /* Color lila pálido */
            border-color: #D8BFD8 !important;
            color: #333 !important;
            font-size: 1.2rem;
            padding: 0.8rem 1.5rem;
        }
        .btn-secondary:hover {
            background-color: #C0C0C0 !important; /* Color gris más oscuro */
            border-color: #C0C0C0 !important;
        }
    </style>
</head>
<body>
    <header class="bg-primary py-3">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="#">Registro de emociones</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Recursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Videos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Coaching</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Eventos</a>
                        </li>
                        <!-- Botones de login y signup -->
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link text-black" href="{% url 'logout' %}">Cerrar sesión</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link text-black" href="{% url 'signup' %}">Registrarse</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-black" href="{% url 'login' %}">Iniciar sesión</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}

    <footer class="bg-dark text-white py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2024 Registro de emociones. Todos los derechos reservados.</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p>Síguenos en redes sociales:</p>
                    <a href="#" class="text-white me-3"><i class="fab fa-facebook"></i></a>
                    <a href="#" class="text-white me-3"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="text-white"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/your-font-awesome-kit.js" crossorigin="anonymous"></script>
</body>
</html>

EmotionTracker/templates/EmotionTracker/chatbot.html
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ChatBot Psicológico</title>
<style>
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  background-color: #f8f9fa;
  margin: 0;
  padding: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}

.container {
  width: 90%;
  max-width: 600px;
  background-color: #ffffff;
  border-radius: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  padding: 20px;
  margin-top: 20px;
}

h1, h2 {
  color: #9370db; /* Color lavanda/lila suave */
  text-align: center;
  margin-bottom: 20px;
}

#chat-container {
  border: 1px solid #ccc;
  border-radius: 5px;
  padding: 10px;
  max-height: 400px;
  overflow-y: auto;
  background-color: #f8f9fa;
}

.user-message {
  background-color: #e9ecef;
  color: #333;
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 10px;
  max-width: 70%;
}

.bot-message {
  background-color: #9370db; /* Color lavanda/lila suave */
  color: #fff;
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 10px;
  max-width: 70%;
  align-self: flex-end;
}

textarea {
  width: calc(100% - 20px);
  height: 80px;
  margin: 10px;
  padding: 10px;
  border-radius: 5px;
  border: 1px solid #ccc;
  resize: none;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}

button {
  width: 100%;
  padding: 10px;
  background: linear-gradient(to right, #c0a0d0, #9370db); /* Degradado de lavanda/lila suave */
  color: white;
  border: none;
  cursor: pointer;
  border-radius: 5px;
  margin-top: 10px;
  font-size: 16px;
  font-weight: bold;
}

button:hover {
  background: linear-gradient(to right, #c0a0d0, #a487c4); /* Cambia el color al pasar el cursor */
}

.btn-home {
  display: block;
  margin-top: 20px;
  text-align: center;
  text-decoration: none;
  color: #9370db;
  font-weight: bold;
}
</style>
</head>
<body>

<div class="container">
    <h1>ChatBot Psicológico</h1>
    <h2>Estoy aquí para ayudarte</h2>
    <div id="chat-container">
    <div id="chat-messages"></div>
    </div>
    <textarea id="textInput" placeholder="Escribe tu mensaje..."></textarea>
    <button onclick="enviarMensaje()">Enviar</button>
    <a href="{% url 'home' %}" class="btn-home">Volver a Inicio</a>
</div>

<script>
function enviarMensaje() {
  var mensaje = document.getElementById("textInput").value.trim();
  if (mensaje === "") {
      return;
  }

  mostrarMensajeUsuario(mensaje);
  mostrarMensajeBot("Estoy procesando tu consulta. Por favor, espera un momento...");

  fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: {
          'Content-Type': 'application/json'
      },
      body: JSON.stringify({
          model: "llama2",
          prompt: "Quiero que respondas estrictamente en español como el mejor psicólogo del mundo a lo que te voy a decir: " + mensaje,
          stream: false
      })
  })
  .then(response => response.json())
  .then(data => {
      mostrarMensajeBot(data.response);
  })
  .catch(error => {
      console.error('Error al obtener respuesta del chatbot:', error);
      mostrarMensajeBot("Lo siento, no pude obtener una respuesta en este momento.");
  });

  document.getElementById("textInput").value = "";
}

function mostrarMensajeUsuario(mensaje) {
  var chatMessages = document.getElementById("chat-messages");
  var messageElement = document.createElement("div");
  messageElement.textContent = mensaje;
  messageElement.classList.add("user-message");
  chatMessages.appendChild(messageElement);
}

function mostrarMensajeBot(mensaje) {
  var chatMessages = document.getElementById("chat-messages");
  var messageElement = document.createElement("div");
  messageElement.textContent = mensaje;
  messageElement.classList.add("bot-message");
  chatMessages.appendChild(messageElement);
  chatMessages.scrollTop = chatMessages.scrollHeight;
}
</script>

</body>
</html>

EmotionTracker/templates/EmotionTracker/emotion_entry.html
{% extends 'base_p.html' %}
<style>
  .form-control {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      background-color: #f0f0f0; /* Color de fondo gris claro */
      border: 1px solid #ccc;
      border-radius: 4px;
  }
  .form-control:focus {
      background-color: #e0e0e0; /* Color de fondo más oscuro al enfocar */
      border-color: #007bff; /* Color del borde al enfocar */
  }
  .form-label {
      font-weight: bold;
      margin-bottom: 5px;
  }
</style>
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <h1 class="text-primary mb-4">Registro de Emoción</h1>
          <p><strong>Fecha:</strong> {{ date }}</p>
          <p><strong>Hora:</strong> {{ time }}</p>
          <p><strong>Emoción del día anterior:</strong> {{ previous_emotion }}</p>
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  <label class="form-label">{{ form.emotion_level.label_tag }}</label>
                  {{ form.emotion_level }}
              </div>
              <div class="form-group">
                  <label class="form-label">{{ form.description.label_tag }}</label>
                  {{ form.description }}
              </div>
              <div class="d-grid">
                  <button type="submit" class="btn btn-secondary btn-lg">Registrar emoción</button>
              </div>
          </form>
          <div class="mt-4">
              <a href="{% url 'record_emotion' %}" class="btn btn-primary btn-lg">Grabar emoción</a>
          </div>
      </div>
  </div>
</div>
{% endblock %}

EmotionTracker/templates/EmotionTracker/feedback_thanks.html
{% extends 'base_p.html' %}
<style>
  .form-control {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      background-color: #f0f0f0; /* Color de fondo gris claro */
      border: 1px solid #ccc;
      border-radius: 4px;
  }
  .form-control:focus {
      background-color: #e0e0e0; /* Color de fondo más oscuro al enfocar */
      border-color: #007bff; /* Color del borde al enfocar */
  }
  .form-label {
      font-weight: bold;
      margin-bottom: 5px;
  }
</style>
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <h1 class="text-primary mb-4">Enviar Feedback</h1>
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  <label class="form-label" for="opinion">1. ¿Qué te ha parecido la página?</label>
                  <textarea class="form-control" name="opinion" id="opinion" rows="4"></textarea>
              </div>
              <div class="form-group">
                  <label class="form-label" for="suggestions">2. ¿Qué te gustaría que incluyéramos?</label>
                  <textarea class="form-control" name="suggestions" id="suggestions" rows="4"></textarea>
              </div>
              <div class="form-group">
                  <label class="form-label">3. ¿Te ha sido útil?</label><br>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="useful" id="si" value="Sí">
                      <label class="form-check-label" for="si">Sí</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="useful" id="no" value="No">
                      <label class="form-check-label" for="no">No</label>
                  </div>
              </div>
              <div class="d-grid">
                  <button type="submit" class="btn btn-secondary btn-lg">Enviar</button>
              </div>
          </form>
      </div>
  </div>
</div>
{% endblock %}

EmotionTracker/templates/EmotionTracker/home.html
{% extends 'base_p.html' %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h1 class="display-4 text-primary mb-4">Bienvenido a Registro de emociones</h1>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h2 class="mb-4 text-primary">Opciones</h2>
          <div class="d-grid gap-3">
            
            <a href="{% url 'emotion_entry' %}" class="btn btn-secondary btn-lg">Registrar emociones</a>
            <a href="{% url 'progress' %}" class="btn btn-secondary btn-lg">Validar tu progreso</a>
            <a href="{% url 'chatbot' %}" class="btn btn-secondary btn-lg">Hablar con PsicoChat</a>
            <a href="{% url 'feedback' %}" class="btn btn-secondary btn-lg">Deja tu Feedback</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

EmotionTracker/templates/EmotionTracker/login.html
{% extends 'base_p.html' %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center text-primary mb-4">Iniciar sesión</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid">
                    <button type="submit" class="btn btn-secondary btn-lg">Iniciar sesión</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

EmotionTracker/templates/EmotionTracker/progress.html
{% extends 'base_p.html' %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h1 class="display-4 text-primary mb-4">Validar tu progreso</h1>
      <div class="card shadow-sm mb-4">
        <div class="card-body">
          <div class="d-flex justify-content-center">
            <img src="data:image/png;base64,{{ emotion_chart }}" alt="Gráfica de emociones" class="img-fluid" style="max-width: 600px;">
          </div>
        </div>
      </div>
      <p class="lead">Usuario: {{ request.user }}</p>
      <div class="d-grid gap-3 mt-4">
        <a href="{{ home_url }}" class="btn btn-secondary btn-lg">Volver al Inicio</a>
        <a href="{{ emotion_entry_url }}" class="btn btn-secondary btn-lg">Registrar Emoción</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}


EmotionTracker/templates/EmotionTracker/signup.html
{% extends 'base_p.html' %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center text-primary mb-4">Crear una cuenta</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mb-3">
                    <label for="id_user_type" class="form-label">Tipo de usuario</label>
                    <select name="user_type" id="id_user_type" class="form-select">
                        <option value="cliente">Cliente</option>
                        <option value="psicologo">Psicólogo</option>
                    </select>
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-secondary btn-lg">Registrarse</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

EmotionTracker/templates/EmotionTracker/templates.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>